In [1]:
import numpy as np

In [2]:
a = np.arange(25).reshape(5,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
a[4,:]

array([20, 21, 22, 23, 24])

In [5]:
a[:,[1,3]]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [11]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [10]:
a[[1,3],[0,2]]

array([ 5, 17])

In [12]:
a[1::2,:3:2]

array([[ 5,  7],
       [15, 17]])