In [1]:
import numpy as np

In [2]:
a = np.arange(25).reshape(5,5)

In [3]:
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

In [4]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [12]:
"""
Dow Selection
-------------

Topics: Boolean array operators, sum function, where function, plotting.

The array 'dow' is a 2-D array with each row holding the
daily performance of the Dow Jones Industrial Average from the
beginning of 2008 (dates have been removed for exercise simplicity).
The array has the following structure::

       OPEN      HIGH      LOW       CLOSE     VOLUME      ADJ_CLOSE
       13261.82  13338.23  12969.42  13043.96  3452650000  13043.96
       13044.12  13197.43  12968.44  13056.72  3429500000  13056.72
       13046.56  13049.65  12740.51  12800.18  4166000000  12800.18
       12801.15  12984.95  12640.44  12827.49  4221260000  12827.49
       12820.9   12998.11  12511.03  12589.07  4705390000  12589.07
       12590.21  12814.97  12431.53  12735.31  5351030000  12735.31

0. The data has been loaded from a .csv file for you.
1. Create a "mask" array that indicates which rows have a volume
   greater than 5.5 billion.
2. How many are there?  (hint: use sum).
3. Find the index of every row (or day) where the volume is greater
   than 5.5 billion. hint: look at the where() command.

Bonus
~~~~~

1. Plot the adjusted close for *every* day in 2008.
2. Now over-plot this plot with a 'red dot' marker for every
   day where the volume was greater than 5.5 billion.

See :ref:`dow-selection-solution`.
"""

pass

In [7]:
from numpy import loadtxt, sum, where
import matplotlib.pyplot as plt
# Constants that indicate what data is held in each column of
# the 'dow' array.
OPEN = 0
HIGH = 1
LOW = 2
CLOSE = 3
VOLUME = 4
ADJ_CLOSE = 5

# 0. The data has been loaded from a .csv file for you.

# 'dow' is our NumPy array that we will manipulate.
dow = loadtxt('./exercises/dow_selection/dow.csv', delimiter=',')



In [9]:
dow.shape

(168, 6)

In [ ]:
# 1. Create a "mask" array that indicates which rows have a volume
#    greater than 5.5 billion.

dow[dow>5.5e9]



In [11]:
dow>5.5e9

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ..., 
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], dtype=bool)

In [14]:
dow[:,4]

array([  3.45265000e+09,   3.42950000e+09,   4.16600000e+09,
         4.22126000e+09,   4.70539000e+09,   5.35103000e+09,
         5.17049000e+09,   4.49584000e+09,   3.68209000e+09,
         4.60164000e+09,   5.44062000e+09,   5.30313000e+09,
         6.00484000e+09,   6.54469000e+09,   3.24168000e+09,
         5.73530000e+09,   4.88225000e+09,   4.10093000e+09,
         4.23296000e+09,   4.74276000e+09,   4.97029000e+09,
         4.65077000e+09,   3.49578000e+09,   4.31574000e+09,
         4.00812000e+09,   4.58916000e+09,   3.76849000e+09,
         3.59314000e+09,   4.04464000e+09,   3.85642000e+09,
         3.64476000e+09,   3.58330000e+09,   3.61355000e+09,
         3.87052000e+09,   3.69666000e+09,   3.57266000e+09,
         3.86635000e+09,   4.09606000e+09,   3.90470000e+09,
         3.93858000e+09,   4.42673000e+09,   4.11757000e+09,
         4.75718000e+09,   4.27771000e+09,   4.32346000e+09,
         4.56541000e+09,   4.26124000e+09,   5.10908000e+09,
         4.41428000e+09,

In [16]:
mask = dow[:,4]>5.5e9

In [17]:
# 2. How many are there?  (hint: use sum).
np.sum(mask)

18

In [18]:


# 3. Find the index of every row (or day) where the volume is greater
#    than 5.5 billion. hint: look at the where() command.


np.where(mask)

(array([ 12,  13,  15,  51,  54, 123, 125, 129, 131, 132, 134, 135, 136,
        137, 139, 140, 141, 145]),)

In [10]:

# BONUS:
# a. Plot the adjusted close for EVERY day in 2008.
# b. Now over-plot this plot with a 'red dot' marker for every
#    day where the volume was greater than 5.5 billion.


