In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a[[0,3]]

array([0, 3])

In [4]:
a[[0,1,3]]

array([0, 1, 3])

In [7]:
b = np.arange(12).reshape(4,3)

In [8]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
b[[0],[2]]

array([2])

In [11]:
b[[0,2],[2,0]] #0,2 is the first location, 2,0 is the second location

array([2, 6])

In [13]:
c =  np.arange(24).reshape(2,3,4)

In [15]:
c[[0,1],[1,1],[2,1]]

array([ 6, 17])

## math

In [16]:
c > 16

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False,  True,  True,  True],
        [ True,  True,  True,  True]]], dtype=bool)

In [17]:
c[c>16]

array([17, 18, 19, 20, 21, 22, 23])

In [18]:
d = c[:,1:2,1:3]

In [19]:
d

array([[[ 5,  6]],

       [[17, 18]]])

In [21]:
d.flags #owndata is false, d is direct reference to c

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [22]:
#change in d will change c
d[0,0,0]=1000

In [23]:
c

array([[[   0,    1,    2,    3],
        [   4, 1000,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [24]:
e = c[c>16]

In [25]:
e.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [28]:
d1 = d.reshape(4,1)

In [30]:
d1.flags #change the structure not the number, still not own the data

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [ ]:
# c is reference to np.arange, not owndata too
# nparnge: header/ array
# reshape: create a new header with new shape, point to arange array