In [1]:
%matplotlib inline

In [2]:
test_list = list(range(1000))

In [3]:
import numpy as np

In [5]:
test_array=np.arange(1000)

In [6]:
%timeit sum(test_list)

4.19 µs ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
#10~100 time faster
%timeit test_array.sum()

2.04 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
%timeit np.sum(test_array)

2.89 µs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
#1 python list: store pointer to memory (not in order)
#  nplist: store value ordered in memory
#2 python list: sum: check integer/string first (for every element) ..need time
#  nplist: fixed datatype (float, int32, int64), write in C
# python list: hetergenors/resized
# nparray: homogeneous/fixed size (or very expensive operation)

In [10]:
a = np.array([-1,0,1,100],dtype='int8')

In [11]:
a

array([ -1,   0,   1, 100], dtype=int8)

In [12]:
1/0

ZeroDivisionError: division by zero

In [13]:
a/0

/Users/sunli/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/sunli/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-inf,  nan,  inf,  inf])

In [14]:
100 ** 2

10000

In [15]:
100 ** 4

100000000

In [18]:
100 ** 20 #as large as you want

10000000000000000000000000000000000000000

In [19]:
a ** 2 ##100^2 in int8 will overflow

array([ 1,  0,  1, 16], dtype=int8)

In [20]:
b = a.astype('float32')

In [21]:
b

array([  -1.,    0.,    1.,  100.], dtype=float32)

In [22]:
b/0

/Users/sunli/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/sunli/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-inf,  nan,  inf,  inf], dtype=float32)

In [23]:
np.nan == np.nan

False

In [24]:
np.isnan(np.nan)

True

In [25]:
np.zeros(200)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [26]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
np.empty((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

### extract data

In [28]:
a

array([ -1,   0,   1, 100], dtype=int8)

In [29]:
a[0]

-1

In [30]:
a[-1]

100

In [31]:
a[:2]

array([-1,  0], dtype=int8)

In [32]:
a[::2]

array([-1,  1], dtype=int8)

In [33]:
a[-1] = 5 #mutable

In [34]:
a

array([-1,  0,  1,  5], dtype=int8)

In [35]:
b = np.arange(12).reshape(4,3)

In [36]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
b.shape

(4, 3)

In [38]:
b[2][2]

8

In [39]:
b[2,2] #use this

8

In [40]:
b[:2,:2]

array([[0, 1],
       [3, 4]])

In [41]:
b[:2][:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
b[1:3,-1] #collapse to one demension

array([5, 8])

In [43]:
b[1:3,-1:] #keep the data demension

array([[5],
       [8]])

In [44]:
b[1:3,:-1]

array([[3, 4],
       [6, 7]])

In [45]:
(2)

2

In [46]:
2,

(2,)

In [47]:
b[:1,:1]

array([[0]])

In [50]:
np.loadtxt

<function numpy.lib.npyio.loadtxt>

In [51]:
c = np.arange(24).reshape(2,3,4)

In [52]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
c[1,1,1]

17

In [54]:
c[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
c[1,0,:]

array([12, 13, 14, 15])

In [58]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])