## operations

In [1]:
import numpy as np

In [2]:
a = np.arange(25).reshape(5,5)

In [3]:
a + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [4]:
a + a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [5]:
a + np.arange(7)

ValueError: operands could not be broadcast together with shapes (5,5) (7,) 

In [6]:
#broadcast
a + np.arange(5)

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23],
       [20, 22, 24, 26, 28]])

In [8]:
np.arange(5).reshape(5,1)+np.arange(1,5)

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [10]:
np.arange(5).reshape(5,1)+np.arange(5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [11]:
# rule 1: make sure size match 
# rule 2: operation done element wise
# rule 3: nan
# rule 4: axis collapse demesion you choose

In [12]:
a = a.astype('float64')

In [13]:
a[2,3]=np.nan

In [14]:
a + 5

array([[  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  nan,  19.],
       [ 20.,  21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.,  29.]])

In [15]:
np.sum(a)

nan

In [17]:
np.sum(a,axis=0)

array([ 50.,  55.,  60.,  nan,  70.])

In [18]:
b = np.arange(12).reshape(4,3)

In [19]:
np.sum(b,axis = 0)

array([18, 22, 26])

In [20]:
np.sum(b,axis = -1)

array([ 3, 12, 21, 30])

In [21]:
np.sum(b,axis = 1)

array([ 3, 12, 21, 30])